name: CI Test Robot

on: [push]  # Triggers the robot every time you push code

jobs:
  my-first-job:
    runs-on: ubuntu-latest  # Borrows a Linux computer from GitHub
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Downloads your code to that computer

      - name: Say Hello
        run: echo "Hello OpenPrinting! The robot is working."

      - name: Check Tools
        run: |
          gcc --version
          make --version
